config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: [:show
  ]
  get 'welcome/index'

  get 'welcome/about'

  root 'welcome#index'

  resources :topics do
    resources :bookmarks, except: [:index] do
      resources :likes, only: [:index, :create, :destroy]
    end
  end

  post :incoming, to: 'incoming#create'

end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user
  has_many :likes, dependent: :destroy

  before_save :format_url
  validates :url, :presence => true
  default_scope { order('created_at DESC') }


  private

  def format_url
    unless self.url[/\Ahttp:\/\//] || self.url[/\Ahttps:\/\//]
      self.url = "http://#{self.url}"
    end
  end
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :bookmark

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]
  belongs_to :user
  has_many :bookmarks, dependent: :destroy
  validates :title, :presence => true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :confirmable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:login]

  has_many :topics, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_bookmarks, through: :likes, source: :bookmark

  attr_accessor :login

  validates :username,
   :presence => true,
   :uniqueness => {
     :case_sensitive => false
   }

  validates :name, :presence => true

 validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true

  def self.find_for_database_authentication(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions.to_hash).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      elsif conditions.has_key?(:username) || conditions.has_key?(:email)
        where(conditions.to_hash).first
      end
  end

  def liked(bookmark)
    likes.where(bookmark_id: bookmark.id).first
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :name, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :name, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def show
    @bookmark = Bookmark.find(params[:id])
  end

  def new
    @bookmark = Bookmark.new
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.topic = @topic
    @bookmark.user = current_user
    authorize @bookmark

    if @bookmark.save
      flash.now[:alert] = "Bookmark added successfully."
      redirect_to @topic
    else
      flash.now[:error] = "Error creating bookmark. Please try again."
      render :new
    end

  end

  def edit
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.find(params[:id])
    authorize @bookmark
  end

  def update
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.find(params[:id])
    authorize @bookmark
    @bookmark.update_attributes(bookmark_params)
    if @bookmark.save
      redirect_to @topic, notice: "Bookmark updated succesfully."
    else
      flash.now[:error] = "Error updating bookmark. Please try again."
      render :edit
    end
  end

  def destroy
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.find(params[:id])
    authorize @bookmark
    if @bookmark.destroy
      flash[:notice] = "Bookmark was deleted successfully."
      redirect_to @bookmark.topic
    else
      flash.now[:error] = "There was an error deleting the bookmark."
      render @topic
    end

  end

  def bookmark_params
    params.require(:bookmark).permit(:url, :topic_id)
  end
end

app/controllers/incoming_controller.rb
class IncomingController < ApplicationController

  skip_before_action :verify_authenticity_token, only: [:create]

  def create

    @user = User.find_by(email: params[:sender])

    @topic = Topic.find_by(title: params[:subject])

    @url = params["body-plain"]

    if @user == nil
      @user = User.new
      @user.email = params[:sender]
      @user.name = "New User"
      @user.password = 'password'
      @user.save!
    end

    if @topic == nil
      @topic = Topic.new
      @topic.title = params[:subject]
      @topic.user_id = @user.id
      @topic.save!
    end

    @bookmark = Bookmark.new
    @bookmark.topic_id = @topic.id
    @bookmark.url = @url.strip
    @bookmark.user = @user
    @bookmark.save!

    head 200
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def index
    likes = Like.where(user_id: current_user_id)
  end

  def new
    like = Like.new
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.find(params[:bookmark_id])
    @like = current_user.likes.build(bookmark: @bookmark)

    if @like.save
      flash[:notice] = "Bookmark liked!"
      redirect_to [@bookmark.topic]
    else
      flash.now[:error] = "Error unliking. Please try again."
      redirect_to [@bookmark.topic]
    end
  end

  def destroy
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.find(params[:bookmark_id])
    @like = current_user.likes.find_by(bookmark_id: @bookmark.id)

    if @like.destroy
      flash[:notice] = "Bookmark unliked!"
      redirect_to [@bookmark.topic]
    else
      flash.now[:error] = "Error unliking. Please try again."
      redirect_to [@bookmark.topic]
    end
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  include Pundit
  # before_action :authenticate_user!, except: [ :show, :index ]

  def index
    @topics = Topic.all
  end

  def show
    @topic = Topic.find(params[:id])
    @bookmarks = @topic.bookmarks
  end

  def new
    @topic = Topic.new
  end

  def edit
  end

  def create
    @topic = Topic.new(topic_params)
    @topic.user = current_user
    if @topic.save
      redirect_to @topic, notice: "Topic added succesfully."
    else
      flash.now[:error] = "Error creating topic. Please try again."
      render @topics
    end
  end

  def destroy
    @topic = Topic.find(params[:id])
    authorize @topic
    if @topic.destroy
      flash[:notice] = "\"#{@topic.title}\" was deleted successfully."
      redirect_to action: :index
    else
      flash[:error] = "There was an error deleting the topic."
      redirect_to action: :index
    end
  end

  def topic_params
    params.require(:topic).permit(:title)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user_bookmarks = current_user.bookmarks
    @liked_bookmarks = current_user.liked_bookmarks
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bookmarks/edit.html.erb
<h1>Edit Bookmark</h1>

<div class="row">
  <div class="col-md-8">
      <%= form_for [@topic, @bookmark] do |f| %>
        <div class="form-group">
          <%= f.label :url %>
          <%= f.text_field :url, class: 'form-control', placeholder: "Enter bookmark url." %>
        </div>
        <div class="form-group">
          <%= f.submit "Save", class: 'btn btn-success' %>
        </div>
      <% end %>
  </div>
</div>

app/views/bookmarks/new.html.erb
<h1>New Bookmark</h1>

<div class="row">
  <div class="col-md-8">
      <%= form_for [@topic, @bookmark], url: topic_bookmarks_path do |f| %>
        <div class="form-group">
          <%= f.label :url %>
          <%= f.text_field :url, class: 'form-control', placeholder: "Enter bookmark url." %>
        </div>
        <div class="form-group">
          <%= f.submit "Save", class: 'btn btn-success' %>
        </div>
      <% end %>
  </div>
</div>

app/views/bookmarks/show.html.erb
<h1>Bookmarks#show</h1>
<p>Find me in app/views/bookmarks/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocmarks</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-default navbar-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Blocmarks", root_path, class: 'navbar-brand' %>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", root_path%></li>
          <li><%= link_to "About", welcome_about_path %></li>
          <li><%= link_to "Topics", topics_path %></li>
          <li class="dropdown">
          <% if user_signed_in? %>
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name %><b class="caret"></b></a>
              <ul class="dropdown-menu">
                  <li><%= link_to "View profile", current_user %></li>
                  <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
                  <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
              </ul>
          <% else %>
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">User<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Sign In", new_user_session_path %></li>
                <li><%= link_to "Sign Up", new_user_registration_path %></li>
              </ul>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="section hero">
    <div class="container">
      <div class="flash">
        <% if flash[:notice] %>
          <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= flash[:notice] %>
          </div>
        <% elsif flash.now[:error] %>
          <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= flash.now[:error] %>
          </div>
        <% elsif flash[:alert] %>
          <div class="alert alert-warning">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= flash[:alert] %>
          </div>
        <% end %>
      </div>
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/likes/_like.html.erb
<% if policy(Like.new).create? %>
  <div>
    <% if like = current_user.liked(bookmark) %>
      <%= link_to [bookmark.topic, bookmark, like], class: 'btn btn-danger', method: :delete do %>
        <i class="glyphicon glyphicon-star-empty"> </i>&nbsp; Unlike
      <% end %>
    <% else %>
      <%= link_to [ bookmark.topic, bookmark, Like.new], class: 'btn btn-primary', method: :post do %>
        <i class="glyphicon glyphicon-star"> </i>&nbsp; Like
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/likes/index.html.erb
<h1>Likes#index</h1>
<p>Find me in app/views/likes/index.html.erb</p>

app/views/topics/_form.html.erb
<%= form_for @topic do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Enter topic" %>
  </div>
  <%= f.submit "Save", class: 'btn btn-success' %>
<% end %>

app/views/topics/edit.html.erb
<h1>Topics#edit</h1>
<p>Find me in app/views/topics/edit.html.erb</p>

app/views/topics/index.html.erb
<div class="page-header">
  <h1 class="text-center">All Blockmarks</h1>
</div>
<% if policy(@topics).create? %>
  <p><%= link_to "Create Topic", new_topic_path, class: 'btn btn-success' %></p>
<% end %>
<br>
<div class="container">
  <div class="row">
    <% @topics.each do |topic| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <p><%= link_to topic.title, topic %>
              <% if policy(topic).destroy? %>
              - <%= link_to "Delete", topic, method: :delete, class: 'btn btn-danger btn-sm' %></p>
              <% end %>
            <br>
            <small>
              <% topic.bookmarks.each do |bookmark| %>
                <p><%= link_to bookmark.url, bookmark.url, :target => '_blank' %></p>
                <br>
              <% end %>
            </small>
          </h4>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<div class="row">
  <div class="col-md-8">
      <%= form_for @topic do |f| %>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: 'form-control', placeholder: "Enter topic" %>
        </div>
        <%= f.submit "Save", class: 'btn btn-success' %>
      <% end %>
  </div>
</div>  

app/views/topics/show.html.erb
<%= content_tag_for :div, @topic do %>
<h1 class="text-center"><%= "##{@topic.title} "%></h1>
<% if policy(@topic).destroy? %>
  <p class="text-center"><%= link_to "Delete Topic", @topic, method: :delete, class: 'btn btn-danger btn-sm' %></p>
<% end %>
<% if policy(@topic).create? %>
  <p><%= link_to "Create Bookmark", new_topic_bookmark_path(@topic), class: 'btn btn-success' %></p>
<% end %>

<br>
<div class="container">
  <div class="row">
    <ul class="col-md-8">
        <% @bookmarks.each do |bookmark| %>
          <div class="media">
            <div class="media-body">
                <%= link_to bookmark.url, bookmark.url %>
                <% if policy(bookmark).update? %>
                   - <%= link_to "Edit", edit_topic_bookmark_path(@topic, bookmark), class: 'btn btn-primary btn-sm' %>   <%= link_to "Delete", [@topic, bookmark], method: :delete, class: 'btn btn-danger btn-sm' %>
                <% end %>
                <%= render partial: 'likes/like', locals: { bookmark: bookmark } %>
            </div>
          </div>
        <% end %>
      </p>
    </div>
  </div>
</div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<h1>My Bookmarks</h1>
<div class="container">
  <div class="row">
    <h3>Created Bookmarks</h3>
    <ul class="col-md-8">
        <% @user_bookmarks.each do |user_bookmark| %>
          <div class="media">
            <div class="media-body">
              <%= "##{user_bookmark.topic.title}" %>
              <br>
              <%= link_to user_bookmark.url, user_bookmark.url, :target => '_blank' %> <%= link_to "Delete", [user_bookmark.topic, user_bookmark], method: :delete, class: 'btn btn-danger btn-sm' %>
            </div>
          </div>
        <% end %>
    </ul>
    </div>
</div>

<div class="container">
  <div class="row">
    <h3>Liked Bookmarks:</h3>
      <div class="col-md-8">
        <% @liked_bookmarks.each do |liked_bookmark| %>
          <p class="media-heading">
            <%="##{liked_bookmark.topic.title}" %>
            <br>
            <%= link_to liked_bookmark.url, liked_bookmark.url, :target => '_blank' %> <%= render partial: 'likes/like', locals: { bookmark: liked_bookmark } %>
            <br>
          </p>
        <% end %>
      </div>
  </div>
</div>

app/views/welcome/about.html.erb
<div class="container">
  <div class="jumbotron">
    <h1 class="text-center">About</h1>
    <p class="text-center">This app was built as an assignment for the Bloc Full Stack Development Course.</p>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="container">
  <div class="jumbotron">
    <h1 class="text-center">Blocmarks:</h1>
    <p class="text-center">Social Bookmarking With Email Integration</p>
  </div>
</div>